### ISSUE TITLE
Listen for changes

### ISSUE THREAD

**Issue by antoniobeltran** [launchdarkly/ruby-server-sdk#173]
Hi, is there a way to listen for and capture change events using ruby server sdk like you can on node.js sdk? I can't find it, though my eyes may be messing with me.

**Comment by eli-darkly** [comment]
Unfortunately, this SDK doesn't yet have that feature. It's one of the features to be added in the next major version release, but we don't have a timetable for that yet.

**Comment by antoniobeltran** [comment]
Thanks for the response @eli-darkly
