### ISSUE TITLE
Fetching custom properties of feature flag

### ISSUE THREAD

**Issue by sanjeevkkn** [launchdarkly/ruby-server-sdk#187]
**Is your feature request related to a problem? Please describe.**
we need to fetch the feature flags custom properties through ruby sdk

**Describe the solution you'd like**
we would love to have separate function call to fetch those custom properties through flag key and custom property key

**Comment by bwoskow-ld** [comment]
Hi @sanjeevkkn,

The `launchdarkly-server-sdk` gem sourced from this repository is primarily intended for the evaluation of feature flags within Ruby applications. We maintain a separate gem, `launchdarkly_api`, which is meant for general usage of LaunchDarkly's REST API. Once you start using the `launchdarkly_api` gem you can use the [`get_feature_flag`](https://github.com/launchdarkly/api-client-ruby/blob/master/lib/launchdarkly_api/api/feature_flags_api.rb#L248) function to get a flag's custom properties. Refer to our [API documentation](https://apidocs.launchdarkly.com/tag/Feature-flags#operation/getFeatureFlag) for more information -- you'll see a top-level `customProperties` object in the response.

Unfortunately it looks like there is currently a syntax error in the `api-client-ruby` repository readme which makes it harder to read, but at the bottom of https://raw.githubusercontent.com/launchdarkly/api-client-ruby/master/README.md you can see sample code of how to use the `launchdarkly_api` gem.

Cheers,
@bwoskow-ld
