### ISSUE TITLE
New Feature Store docs don't match implementation

### ISSUE THREAD

**Issue by michaeldbianchi** [launchdarkly/ruby-server-sdk#194]
The usage reference in comments show you can start call `LaunchDarkly::Integrations::DynamoDB.new_feature_store` with just the table name, but it actually requires 2 args right now. However, I think it'd be more ergonomic if `opts` defaulted to an empty hash.

Suggestion:
Change the new_feature_store function signature to `def self.new_feature_store(table_name, opts = {})`

This appears to not directly impact the other feature store implementations, though it's clear there's some mismatch in design (FileData defaults to empty hash, but  Consul and Redis require `opts` even if it's an empty hash).

Ideally I'd want to not pass in an empty hash. But at the very least, the usage docs should match the implementation

Usage reference:
https://github.com/launchdarkly/ruby-server-sdk/blob/986af21c527092a603c8bb6d6fefa0d1f5135914/lib/ldclient-rb/integrations/dynamodb.rb#L25

**Comment by keelerm84** [comment]
Thank you for reporting this issue. I have filed this as internal ticket sc-142425. We will let you know once we have this resolved!

**Comment by eli-darkly** [comment]
We've released version 6.3.2 with a fix for this.
