### ISSUE TITLE
Wrong syntax is used for interpolation in log message

### ISSUE THREAD

**Issue by michaeldbianchi** [launchdarkly/ruby-server-sdk#195]
The following line uses `${description}`, which is bash (and other) syntax for interpolation, but Ruby uses `#{description}`.

https://github.com/launchdarkly/ruby-server-sdk/blob/edc4efd15263cf99839e047bea8e0fc1a4f06e22/lib/ldclient-rb/impl/integrations/dynamodb_impl.rb#L38

This results in the following log message:
```
${description}: using DynamoDB table \"<table-name>\"
```
Instead of the interpolating DynamoDB into the message

**Comment by keelerm84** [comment]
Filed internally as sc-142457. We will let you know when this has been resolved.

**Comment by eli-darkly** [comment]
We've released version 6.3.3 with a fix for this.
