### ISSUE TITLE
ldclient-rb gem updates no longer being published to Rubygems

### ISSUE THREAD

**Issue by batter** [launchdarkly/ruby-server-sdk#206]
**Is this a support request?**
Yes

**Describe the bug**
It looks like the latest release for the [`ldclient-rb` gem on Rubygems](https://rubygems.org/gems/ldclient-rb) is `5.5.6`, but the current release of the sdk gem is now `6.4.0`.. Am I to understand that the `ldclient-rb` gem is no longer going to receive updates?

Is the recommended approach to bundle the [`launchdarkly-server-sdk` gem](https://rubygems.org/gems/launchdarkly-server-sdk) instead?

Our LaunchDarkly integration currently displays a banner when we sign in stating that the SDK version we are using is no longer supported, even though we thought we were on the latest release since we have the latest released version of the `ldclient-rb` gem in our application bundle. Please advise, and consider publishing instructions of what to do (or putting instructions somewhere in your docs about that gem being deprecated)

FWIW I personally believe having it as a standalone gem makes sense and makes the integration more modular, like how Rails has `ActiveRecord` as standalone gem which can be used outside of Rails if desired.

**Comment by eli-darkly** [comment]
The gem name was changed three years ago. As described in the [changelog](https://docs.launchdarkly.com/sdk/server-side/ruby) (see 5.5.7) ad the online [reference guide](https://docs.launchdarkly.com/sdk/server-side/ruby), the gem to use is `launchdarkly-server-sdk`.

**Comment by eli-darkly** [comment]
> FWIW I personally believe having it as a standalone gem makes sense and makes the integration more modular, like how Rails has ActiveRecord as standalone gem which can be used outside of Rails if desired.

A standalone gem as opposed to what? I'm not sure of what you're suggesting here.

**Comment by batter** [comment]
Right now in order to get the previous functionality, it looks like you have to bundle in this gem and then do:
```
require 'ldclient-rb'
```

Since it was previously a standalone gem it seems like it would be nice to keep the contents of that directory in the repo as a standalone gem and have it be required into this gem.

**Comment by eli-darkly** [comment]
I'm sorry, I'm still having trouble understanding. The contents of what directory? What is the distinction you're making between the "standalone gem" and "this gem"?

The procedure for using the gem in an application has not changed. The name of the gem has changed. Otherwise it's built just the same as it always was.

**Comment by eli-darkly** [comment]
Again, the gem name has been what it is for over three years now. Plenty of customers have been using this SDK and we haven't had any other reports of this being a problem.

**Comment by batter** [comment]
> The procedure for using the gem in an application has not changed. The name of the gem has changed. Otherwise it's built just the same as it always was.

Ok I inspected the contents of the gem and I see that now. My apologies for misunderstanding. I was confused because the new gem name states it is a `server-sdk` when in actuality it appears that it still primarily a client for interacting with the LaunchDarkly API. I guess I just don't understand the purpose of the name change since under the hood it is still the same:
https://github.com/launchdarkly/ruby-server-sdk/blob/3f95e229762b0acdd982d1a12fb5414a4e9781d7/lib/launchdarkly-server-sdk.rb#L1

Thanks for clarifying this though.

**Comment by eli-darkly** [comment]
> I was confused because the new gem name states it is a server-sdk when in actuality it appears that it still primarily a client for interacting with the LaunchDarkly API

Yes, it's a client in that sense, but it's for use _by server-side code_— for instance, a web application. There's a fundamental distinction in the LaunchDarkly product between server-side SDKs and client-side SDKs; the online documentation discusses this here: https://docs.launchdarkly.com/sdk/concepts/client-side-server-side

We standardized our SDK naming around this distinction several years ago, and changed gem/package/repository names accordingly. Right now the only Ruby SDK we have is a server-side one, but there could be a client-side one in the future to be used in different situations (for instance, a command-line tool written in Ruby), which would then have `client-sdk` in its name.

**Comment by eli-darkly** [comment]
But we left `ldclient-rb` as the module name so that customers wouldn't have to modify all of their `require` lines.
