### ISSUE TITLE
Custom attributes ignored in create_legacy_context 

### ISSUE THREAD

**Issue by Hugo-Hache** [launchdarkly/ruby-server-sdk#212]
I was having issues pushing custom attributes with legacy format of context. By browsing the source code I found this [line](
https://github.com/launchdarkly/ruby-server-sdk/blob/efecdf5a8f3744133ed70a406928c1d2b3ef9e7f/lib/ldclient-rb/context.rb#L419) that ignores attributes other than `:ip, :email, :avatar, :firstName, :lastName, :country`.

I'm not sure to understand what "dedicated instance variables" mentions this comment, and so how would the custom attributes would make it to the context sent to the server.

In case other people are facing the same issue, migrating to the new format and putting custom attributes at the root fixed it for me:

```
client.identify({key: 'key', custom: { customAttribute: 'value' }}) # didn't work

client.identify(LaunchDarkly::LDContext.create({kind: 'user', key: 'key', customAttribute: 'value' })) # works
```

**Comment by keelerm84** [comment]
Hi :wave:!

How are you determining that the custom attributes don't work? Are you evaluating a flag that isn't giving you the expected results? Are the custom attributes not showing up in the LaunchDarkly UI?

> I'm not sure to understand what "dedicated instance variables" mentions this comment, and so how would the custom attributes would make it to the context sent to the server.

`key`, `kind`, `name`, and `anonymous` are stored as instance variables in the built context. Every other property is stored in the attributes hash.

In the block of code you linked to, you can see that we first define the attributes as the custom attributes you provided. Then, if you provided any of the originally pre-defined keys (ip, email, etc), then we override those specific custom attributes.

> In case other people are facing the same issue, migrating to the new format and putting custom attributes at the root fixed it for me:

The two examples you provided aren't actually equivalent. In the original, legacy format, you could target the `customAttribute` directly. In the new version, you would have to access it by `/custom/customAttribute`.

The below 2 would be equivalent.

```js
// Legacy user format
{key: 'key', custom: { customAttribute: 'value' }}

// New kind format
{kind: 'user', key: 'key', customAttribute: 'value'}
```

**Comment by Hugo-Hache** [comment]
Hi @keelerm84,

Thanks for the reactivity, you're right about the syntax (I mistakenly let the custom key in LDContext, edited my original to remove it).

To check the customAttributes change I'm using the contexts detail page of my user https://app.launchdarkly.com/default/<ENV>/contexts/user/User%3A<ID>

Since last Friday I've noticed the new Live Events page, here's what I did and observed:

## Using legacy format
* identify with `client.identify({key: 'User:423f1a81-...', custom: { abTestHugo: 51 }})`
* got live event
```
Attribute viewer
March 20, 2023 11:50 AM

{
  "kind": "user",
  "key": "User:423f1a81-...",
  "abTestHugo": 51
}
```
* but nothing changed on context page
```
RubyClient
Last seen: March 18, 2023 10:54 PM

{
  "kind": "user",
  "key": "User:423f1a81-..."
})
```

## Using new format
* identify with `client.identify(LaunchDarkly::LDContext.create({kind: 'user', key: 'User:423f1a81-...', abTestHugo: 52}))`
* no live event, tried to force it with `client.flush`, still nothing
* closed and restarted console, identify with `client.identify(LaunchDarkly::LDContext.create({kind: 'user', key: 'User:423f1a81-...', abTestHugo: 53}))`
* got live event
```
March 20, 2023 12:03 PM

{
  "kind": "user",
  "key": "User:423f1a81-D372-4736-8a3c-5a3bf67c9a7c",
  "abTestHugo": 53
}
```
* but nothing changed on context page
```
RubyClient
Last seen: March 18, 2023 10:54 PM

{
  "kind": "user",
  "key": "User:423f1a81-d372-4736-8a3c-5a3bf67c9a7c"
}
```

## Use custom attribute in flag

I thought that maybe context page was not showing the latest state, so I updated a flag to have a specific value when abTestHugo was "one of" 53 (53 was the only autosuggestion, so was confident that on LD server the event did modify the custom attribute value of my user). 

Despite the flag rule change (saved), the flag value for 423f1a81 staid the default one, both in context detail page and when requesting it though Ruby client

## Conclusion

It looks like context detail page is not showing the latest value of the context custom attribute ... but the fact that the flag rule doesn't trigger is puzzling me 🤔 

My best guess of what's in LD database is now the suggestions of abTestHugo field when writing the rule.
