### ISSUE TITLE
Ruby SDK evaluates date conditions as false

### ISSUE THREAD

**Issue by zbycz** [launchdarkly/ruby-server-sdk#220]
**Describe the bug**
If i create a date condition such as this in LD UI, this library always evaluates it as false. (We also use React JS client which works fine.)

Example of UI:
<img width="740" alt="Screenshot 2023-06-02 at 15 00 04" src="https://github.com/launchdarkly/ruby-server-sdk/assets/385047/d26d3024-0607-4598-a79d-431972dda96d">
 

**To reproduce**
1. create a new flag with date condition on attribute. It should evaluate to true (ie. past date)
2. ask for this condition in Ruby code
3. observe false

**SDK version**
7.2.0

**Language version, developer tools**
ruby 3.2.0

**Comment by keelerm84** [comment]
My apologies for the error, and thank you for reporting this. I will update you once I have a resolution for you.

Tracking internally as sc-205433.

**Comment by keelerm84** [comment]
@zbycz some quick internal testing seems to indicate this is working as expected.

Can you please show me the context you are trying to evaluate? Are you providing the date in the context in RFC 3339 format or as milliseconds?

Are there additional rules on that flag configuration, or is it solely targeting on that date?
