### ISSUE TITLE
Add `observer` to the SDK's gemspec to avoid warnings in ruby 3.3/support ruby 3.4

### ISSUE THREAD

**Issue by dgollahon** [launchdarkly/ruby-server-sdk#271]
**Describe the bug**
I get the following warning in ruby 3.3.1 using sdk version 7.2.0 (but looks to still apply on master):

> warning: [...]/lib/ruby/3.3.0/observer.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add observer to your Gemfile or gemspec. Also contact author of launchdarkly-server-sdk-7.2.0 to add observer into its gemspec.

**To reproduce**
Require the gem with `$VERBOSE = true` on ruby 3.3.x

**Expected behavior**
No warnings are emitted.

**Logs**
N/A

**SDK version**
7.2.0

**Language version, developer tools**
Ruby 3.3.1

**OS/platform**
MacOS

**Additional context**
N/A

**Comment by keelerm84** [comment]
Thank you for bringing this to our attention. I will make sure it gets addressed soon and will let you know once it has been resolved.

**Comment by keelerm84** [comment]
This has been resolved in 8.4.1

**Comment by dgollahon** [comment]
Thank you!
